export const SHOW_INTRO = "SHOW_INTRO";
export const HIDE_INTRO = "HIDE_INTRO";
export const GET_USER = "GET_USER";

export const SET_FX_PARAMETERS = "SET_FX_PARAMETERS";
export const GET_FXRATE = "GET_FXRATE";
export const SET_TRANSACTION_TYPE = "SET_TRANSACTION_TYPE";
export const SET_STARTEND_DATES = "SET_STARTEND_DATES";
export const SET_RECEIVING_METHOD = "SET_RECEIVING_METHOD";
export const SET_PAYMENT_OPTION = "SET_PAYMENT_OPTION"

export const GET_RECIPENTS = "GET_RECIPENTS"
export const GET_RECIPENT = "GET_RECIPENT";
export const SELECT_RECIPENT = "SELECT_RECIPENT";
export const ADD_RECIPENT = "ADD_RECIPENT";
export const ADD_BANK_INFO = "ADD_BANK_INFO";
export const UPDATE_BANK_INFO = "UPDAT_BANK_INFO"