export const SHOW_INTRO = "SHOW_INTRO";
export const HIDE_INTRO = "HIDE_INTRO";
export const GET_USER = "GET_USER";

export const SET_FX_PARAMETERS = "SET_FX_PARAMETERS";
export const GET_FXRATE = "GET_FXRATE";
export const SET_TRANSACTION_TYPE = "SET_TRANSACTION_TYPE";
export const SET_STARTEND_DATES = "SET_STARTEND_DATES";
export const SET_RECEIVING_METHOD = "SET_RECEIVING_METHOD";
export const SET_PAYMENT_OPTION = "SET_PAYMENT_OPTION";
export const SET_RECEIVE_TYPE = "SET_RECEIVE_TYPE"
export const CALCULATION_TYPE = "CALCULATION_TYPE"
export const SET_REFERENCE = "SET_REFERENCE"

export const GET_RECIPIENTS = "GET_RECIPIENTs"
export const GET_RECIPIENT = "GET_recipient";
export const SELECT_RECIPIENT = "SELECT_RECIPIENT";
export const ADD_RECIPIENT = "ADD_RECIPIENT";
export const UPDATE_RECIPIENT = "UPDATE_RECIPIENT"
export const ADD_BANK_INFO = "ADD_BANK_INFO";
export const UPDATE_BANK_INFO = "UPDATE_BANK_INFO"

export const GET_TRANSACTIONS = "GET_TRANSACTIONS"